### ISSUE TITLE
Duda variable consumo casa

### ISSUE THREAD

**Issue by pocoyo01** [mainakae/ingeteam#1]
Hola he conectado mi ingeteam (como el del tutorial) con mi home asistan siguiendo tus instrucciones ( he usado tu json) pero tengo una duda, cual es la variable del consumo de la casa? La verdad no lo tengo muy claro si es directa o hay que realizar operaciones con otras ( ademas tengo baterías y no sabria que variables usar)  Saludos

**Comment by mainakae** [comment]
Hola, la variable que buscas es "consumption".

Saludos!

**Comment by mainakae** [comment]
Acabo de subir una version v2 con esas variables. No me había dado cuenta que no he actualizado en un tiempo el repo.

**Comment by mainakae** [comment]
Version v2 subida, con variables "consumption" y "self_consumption".
